//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsDatesView
    {
        public int TransactionID { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int DateTimeLookupId { get; set; }
        public System.DateTime Date { get; set; }
    }
}
