//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallDown.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarloniusEntities : DbContext
    {
        public CarloniusEntities()
            : base("name=CarloniusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FallDown_HiScore> FallDown_HiScore { get; set; }
    
        public virtual ObjectResult<FallDown_GetNHiScores_Result> FallDown_GetNHiScores(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FallDown_GetNHiScores_Result>("FallDown_GetNHiScores", nParameter);
        }
    }
}
