//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallDown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FallDown_HiScore
    {
        public int HiScoreId { get; set; }
        public int HiScoreValue { get; set; }
        public System.DateTime DateTime { get; set; }
        public string HiScoreName { get; set; }
    }
}
